### ISSUE TITLE
Crashes game when trying to open inventory

### ISSUE THREAD

**Issue by owenklijnsma** [Andrew6rant/Better-Trim-Tooltips#1]
[12:52:55] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:955) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[1.20.2-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.Optional net.minecraft.class_8053.method_48428(net.minecraft.class_5455, net.minecraft.class_1799)'
	at net.minecraft.class_8053.handler$zdg000$better-trim-tooltips$appendTooltip(class_8053.java:533) ~[client-intermediary.jar:?]
	at net.minecraft.class_8053.method_48425(class_8053.java:127) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.method_7950(class_1799.java:657) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25408(class_437.java:226) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_51454(class_465.java:187) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_2380(class_465.java:182) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_25394(class_490.java:88) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:946) ~[client-intermediary.jar:?]
	... 6 more

**Comment by Disketaa** [comment]
+1 

`[05:08:08] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:955) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[1.20.2-0.14.23.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.23.jar:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.Optional net.minecraft.class_8053.method_48428(net.minecraft.class_5455, net.minecraft.class_1799)'
	at net.minecraft.class_8053.handler$zdl000$better-trim-tooltips$appendTooltip(class_8053.java:533) ~[client-intermediary.jar:?]
	at net.minecraft.class_8053.method_48425(class_8053.java:127) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.method_7950(class_1799.java:657) ~[client-intermediary.jar:?]
	at net.minecraft.class_481.method_51454(class_481.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_2380(class_465.java:182) ~[client-intermediary.jar:?]
	at net.minecraft.class_481.method_25394(class_481.java:770) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:946) ~[client-intermediary.jar:?]
	... 6 more`

**Comment by NikSneMC** [comment]
+1

Minecraft 1.20.2
Quilt Loader 0.21.2-1.20.2
Fabric API 0.90.7+1.20.2

```
Description: Rendering screen

java.lang.NoSuchMethodError: 'java.util.Optional net.minecraft.class_8053.method_48428(net.minecraft.class_5455, net.minecraft.class_1799)'
	at net.minecraft.class_8053.handler$bmh000$better-trim-tooltips$appendTooltip(class_8053.java:533)
	at net.minecraft.class_8053.method_48425(class_8053.java:127)
	at net.minecraft.class_1799.method_7950(class_1799.java:657)
	at net.minecraft.class_481.method_51454(class_481.java:781)
	at net.minecraft.class_465.method_2380(class_465.java:182)
	at net.minecraft.class_481.method_25394(class_481.java:770)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:946)
	at net.minecraft.class_310.method_1523(class_310.java:1275)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
```

**Comment by sternschnaube** [comment]
![image](https://github.com/Andrew6rant/Better-Trim-Tooltips/assets/120551916/b6449802-cacb-466d-aee9-15afbd7285ef)
